import StarIcon from '@mui/icons-material/Star';
import product1 from '../images/Windows-10-home.png'
const data = [
    {
      id:1,
      img: product1,
      title: "Microsoft Windows 10",
      star: <StarIcon className='rating-star' />,
      reviews: "(123 reviews)",
      prevPrice: "$199.99",
      newPrice: "149.99",
      company: "Microsoft",
      category: "Operating System (OS)",
    },
    {
      id:2,
      img: "https://m.media-amazon.com/images/I/71eXRG7J2TL.__AC_SY445_SX342_QL70_ML2_.jpg",
      title: "Norton Antivirus 2023",
      star: <StarIcon className='rating-star' />,
      reviews: "(89 reviews)",
      prevPrice: "$79.99",
      newPrice: "59.99",
      company: "Norton",
      category: "Antivirus Software",
    },
    {
      id:3,
        img: "https://m.media-amazon.com/images/I/71Sf9lNE10L._AC_SY741_.jpg",
        title: "Adobe Photoshop CC",
        star: <StarIcon className='rating-star' />,
        reviews: "(325 reviews)",
        prevPrice: "$249.99",
        newPrice: "199.99",
        company: "Adobe",
        category: "Graphic Design Software",
      },
      {
        id:4,
        img: "",
        title: "Bitdefender Total Security 2023",
        star: <StarIcon className='rating-star' />,
        reviews: "(78 reviews)",
        prevPrice: "$89.99",
        newPrice: "69.99",
        company: "Bitdefender",
        category: "Antivirus Software",
      },
      {
        id:5,
        img: "",
        title: "Apple macOS Monterey",
        star: <StarIcon className='rating-star' />,
        reviews: "(110 reviews)",
        prevPrice: "$0.00",
        newPrice: "0.00",
        company: "Apple Inc.",
        category: "Operating System (OS)",
      },
      {
        id:6,
        img: "",
        title: "Autodesk AutoCAD 2023",
        star: <StarIcon className='rating-star' />,
        reviews: "(42 reviews)",
        prevPrice: "$1,690.00",
        newPrice: "1,499.99",
        company: "Autodesk",
        category: "3D Modeling Software",
      },
      {
        id:7,
        img: "",
        title: "Kaspersky Internet Security 2023",
        star: <StarIcon className='rating-star' />,
        reviews: "(56 reviews)",
        prevPrice: "$69.99",
        newPrice: "49.99",
        company: "Kaspersky Lab",
        category: "Antivirus Software",
      },
      {
        id:8,
        img: "",
        title: "Microsoft Office 365",
        star: <StarIcon className='rating-star' />,
        reviews: "(210 reviews)",
        prevPrice: "$149.99/year",
        newPrice: "99.99/year",
        company: "Microsoft",
        category: "Productivity Software",
      },
      {
        id:9,
        img: "",
        title: "Symantec Norton 360 Deluxe",
        star: <StarIcon className='rating-star' />,
        reviews: "(135 reviews)",
        prevPrice: "$89.99",
        newPrice: "69.99",
        company: "Symantec",
        category: "Antivirus Software",
      },
      {
        id:10,
        img: "",
        title: "Linux Ubuntu 22.04 LTS",
        star: <StarIcon className='rating-star' />,
        reviews: "(65 reviews)",
        prevPrice: "$0.00",
        newPrice: "0.00",
        company: "Canonical",
        category: "Operating System (OS)",
      },
      {
        id:11,
        img: "",
        title: "Adobe Illustrator CC",
        star: <StarIcon className='rating-star' />,
        reviews: "(156 reviews)",
        prevPrice: "$239.88/year",
        newPrice: "199.99/year",
        company: "Adobe",
        category: "Graphic Design Software",
      },
      {
        id:12,
        img: "",
        title: "McAfee Total Protection 2023",
        star: <StarIcon className='rating-star' />,
        reviews: "(74 reviews)",
        prevPrice: "$79.99",
        newPrice: "59.99",
        company: "McAfee",
        category: "Antivirus Software",
      },
      {
        id:13,
        img: "",
        title: "Apple Final Cut Pro X",
        star: <StarIcon className='rating-star' />,
        reviews: "(98 reviews)",
        prevPrice: "$299.99",
        newPrice: "249.99",
        company: "Apple Inc.",
        category: "Video Editing Software",
      },
      {
        id:14,
        img: "",
        title: "Oracle Database 19c",
        star: <StarIcon className='rating-star' />,
        reviews: "(36 reviews)",
        prevPrice: "$2,000.00",
        newPrice: "1,799.99",
        company: "Oracle",
        category: "Database Management Software",
      },
      {
        id:15,
        img: "",
        title: "CorelDRAW Graphics Suite 2023",
        star: <StarIcon className='rating-star' />,
        reviews: "(48 reviews)",
        prevPrice: "$499.00",
        newPrice: "399.99",
        company: "Corel",
        category: "Graphic Design Software",
      },
      {
        id:16,
        img: "",
        title: "Windows Server 2022",
        star: <StarIcon className='rating-star' />,
        reviews: "(27 reviews)",
        prevPrice: "$1,399.00",
        newPrice: "1,299.99",
        company: "Microsoft",
        category: "Server Operating System",
      },
      {
        id:17,
        img: "",
        title: "ESET NOD32 Antivirus",
        star: <StarIcon className='rating-star' />,
        reviews: "(53 reviews)",
        prevPrice: "$49.99",
        newPrice: "39.99",
        company: "ESET",
        category: "Antivirus Software",
      },
      {
        id:18,
        img: "",
        title: "Microsoft Windows 11",
        star: <StarIcon className='rating-star' />,
        reviews: "(145 reviews)",
        prevPrice: "$199.99",
        newPrice: "179.99",
        company: "Microsoft",
        category: "Operating System (OS)",
      },
      {
        id:19,
        img: "",
        title: "macOS Big Sur",
        star: <StarIcon className='rating-star' />,
        reviews: "(88 reviews)",
        prevPrice: "$0.00",
        newPrice: "0.00",
        company: "Apple Inc.",
        category: "Operating System (OS)",
      },
      {
        id:20,
        img: "",
        title: "Linux Fedora 35",
        star: <StarIcon className='rating-star' />,
        reviews: "(40 reviews)",
        prevPrice: "$0.00",
        newPrice: "0.00",
        company: "Fedora Project",
        category: "Operating System (OS)",
      },
      {
        id:21,
        img: "",
        title: "Android 12",
        star: <StarIcon className='rating-star' />,
        reviews: "(95 reviews)",
        prevPrice: "$0.00",
        newPrice: "0.00",
        company: "Google",
        category: "Mobile Operating System",
      },
      {
        id:22,
        img: "",
        title: "FreeBSD 13.0",
        star: <StarIcon className='rating-star' />,
        reviews: "(25 reviews)",
        prevPrice: "$0.00",
        newPrice: "0.00",
        company: "The FreeBSD Project",
        category: "Operating System (OS)",
      },
  ];
export default data;